name: Build
on:
  push:
  pull_request:
  create:
    tags:
jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: cssdalek
            asset_name: cssdalek-x86_64-linux
          - os: macos-latest
            artifact_name: cssdalek
            asset_name: cssdalek-x86_64-apple-darwin
          - os: windows-latest
            artifact_name: cssdalek.exe
            asset_name: cssdalek-x86_64-windows.exe
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.19"
      - uses: actions/checkout@v5
      - name: Dependencies
        run: go get -t -d ./...
      - name: Test
        run: go test ./... -race -cover
      - name: Build
        run: go build -trimpath -ldflags="$BI_LDFLAGS"
      - name: Release
        uses: svenstaro/upload-release-action@v2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          overwrite: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.event.ref }}
